change-id = 129295

[llvm]
download-ci-llvm = true

[workspace]
members = [
  "noir-video-editing/generate_freivalds_inputs"
]
resolver = "2"

[workspace.package]
version = "1.1.0"
edition = "2021"

[workspace.dependencies]
alloy-sol-types = "0.8.22"
